version: '3'
services:
  web:
    container_name: nginx
    build: .
    ports:
      - "80:80"
    command: nginx -g "daemon off";
    volumes:
      - ./AngularApp\dist:/www:ro
    depends_on:      
      - python_api

  python_api:
    build: 
      context: . 
      dockerfile: Maps3DPythonApi/Dockerfile
    expose:
      - "8000"
    volumes:
      - ./python:/python
    command: gunicorn -w 1 app:app -b :8000 --log-level debug --reload
